[logging]
# General log level
log_level = INFO

[converters]
# List of Enabled Converters
pdf_converter = True
md_converter = True

[pdf_converter]
# Settings specific to the PDF converter
default_engine = nougat
# For context, nougat commonly has problems with missing pages, even when no_skipping is enabled.
replace_missing_pages = True
engine_replace_missing_page = pix2tex

[pdf_converter.nougat]
# Available models: 0.1.0-small, 0.1.0-base
model_tag = 0.1.0-small
batch_size = 4
no_skipping = True
recompute = False
# Two ways to use nougat: 1. nougat server api 2. nougat cli
# Attention: They don't behave exactly the same due to nougat developer's implementation on the code.
# Note:
# 1. The problem is solvable. We can make our own custom version if we have time.
# 2. Currently our own server version is not even faster than the cli version. So we use default CLI for now and will
#    revise the server side code in the future.
use_nougat_server = False
server_port = 8503

[pdf_converter.pix2tex]
; TODO
