[logging]
# General log level
log_level = INFO

[converters]
# List of Enabled Converters
pdf_converter = True
md_converter = True

[pdf_converter]
# Settings specific to the PDF converter
default_engine = nougat
# For context, nougat commonly has problems with missing pages, even when no_skipping is enabled.
replace_missing_pages = True
engine_replace_missing_page = pix2tex

[pdf_converter.nougat]
# Available models: 0.1.0-small, 0.1.0-base
model_tag = 0.1.0-base
batch_size = 4
server_port = 8503
no_skipping = True

[pdf_converter.pix2tex]
; TODO
